
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"
  
  config.vm.provision "shell", inline: <<-SHELL
  wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
  dpkg -i puppet5-release-$(lsb_release -cs).deb
  apt-get -qq update
  apt-get install -y puppet-agent
SHELL
  
end
