### configuration parameters ###
# Vagrant base box to use
VM_BASE_BOX = "bento/ubuntu-18.04"
# amount of RAM for Vagrant box
DEFAULT_RAM = "512"
# number of CPUs for Vagrant box
BOX_CPU_COUNT = "1"
### /configuration parameters ###


nodes = [
#  { :hostname => 'appserver',  :ip => '192.168.56.101'},
#   { :hostname => 'dbserver',   :ip => '192.168.56.102'},
    { :hostname => 'web',        :ip => '192.168.56.103'},
#   { :hostname => 'tst0',    :ip => '192.168.56.104'},
#   { :hostname => 'tst1', :ip => '192.168.56.105'},
#   { :hostname => 'tst2', :ip => '192.168.56.106'},
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = VM_BASE_BOX
      nodeconfig.vm.hostname = node[:hostname]
      #nodeconfig.vm.network :private_network, ip: node[:ip]
      #nodeconfig.vm.network :forwarded_port, guest: 22, host: 22, id: "ssh"
	  #nodeconfig.vm.network :forwarded_port, guest: 22, host: node[:ip][11,3]+"#{22}", id: "ssh"

      if node[:hostname] == "web"
      nodeconfig.vm.network :forwarded_port, guest: 80, host: 8080, id: "web"
      end

      memory = node[:ram] ? node[:ram] : DEFAULT_RAM;
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.customize [
          "modifyvm", :id,
          "--natdnshostresolver1", "on",
          "--cpuexecutioncap", "50",
          "--memory", memory.to_s,
        ]
      end
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
    dpkg -i puppet5-release-$(lsb_release -cs).deb
    apt-get -qq update
    apt-get install -y puppet-agent
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "environments/test/manifests/"
    puppet.manifest_file = "default.pp"
	puppet.module_path = "environments/test/modules/"

  end

end
