### configuration parameters ###
# Vagrant base box to use
VM_BASE_BOX = "bento/ubuntu-18.04"
# amount of RAM for Vagrant box
DEFAULT_RAM = "512"
# number of CPUs for Vagrant box
BOX_CPU_COUNT = "1"
### /configuration parameters ###


nodes = [
  { :hostname => 'appserver',  :ip => '192.168.0.44', :box => 'precise32' },
  { :hostname => 'dbserver',   :ip => '192.168.0.42', :box => 'precise32' },
  { :hostname => 'web',        :ip => '192.168.0.43', :box => 'precise32' },
  { :hostname => 'ex6web2',    :ip => '192.168.0.45', :box => 'precise32' },
  { :hostname => 'ex6static1', :ip => '192.168.0.46', :box => 'precise32' },
  { :hostname => 'ex6static2', :ip => '192.168.0.47', :box => 'precise32' },
]

Vagrant.configure("2") do |config|

  config.vm.define "#{hostname}" do |box|
    box.vm.box = VM_BASE_BOX
    box.vm.hostname = "#{hostname}"

     box.vm.network :private_network, ip: "192.168.56.101"
     box.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"

    appserver.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", DEFAULT_RAM]
      v.customize ["modifyvm", :id, "--name", "appserver"]
    end
  end

  config.vm.define "dbserver" do |dbserver|
    dbserver.vm.box = "bento/ubuntu-18.04"
    dbserver.vm.hostname = 'dbserver'
    dbserver.vm.network :private_network, ip: "192.168.56.102"
    dbserver.vm.network :forwarded_port, guest: 22, host: 10222, id: "ssh"

    dbserver.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "dbserver"]
    end
  end

  config.vm.define "web" do |web|
    web.vm.box = "bento/ubuntu-18.04"
    web.vm.hostname = 'web'
    web.vm.network :private_network, ip: "192.168.56.103"
    web.vm.network :forwarded_port, guest: 22, host: 10322, id: "ssh"
    web.vm.network :forwarded_port, guest: 80, host: 8080, id: "web"

    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web"]
    end
  end

  config.vm.define "tst0" do |tst0|
    tst0.vm.box = "bento/ubuntu-18.04"
    tst0.vm.hostname = 'tst0'
    tst0.vm.network :private_network, ip: "192.168.56.104"
    tst0.vm.network :forwarded_port, guest: 22, host: 10422, id: "ssh"

    tst0.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "tst0"]
    end
  end

  config.vm.define "tst1" do |tst1|
    tst1.vm.box = "bento/ubuntu-18.04"
    tst1.vm.hostname = 'tst1'
    tst1.vm.network :private_network, ip: "192.168.56.105"
    tst1.vm.network :forwarded_port, guest: 22, host: 10522, id: "ssh"

    tst1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "tst1"]
    end
  end

  config.vm.define "tst2" do |tst2|
    tst2.vm.box = "bento/ubuntu-18.04"
    tst2.vm.hostname = 'tst2'
    tst2.vm.network :private_network, ip: "192.168.56.106"
    tst2.vm.network :forwarded_port, guest: 22, host: 10622, id: "ssh"

    tst2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "tst2"]
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
    dpkg -i puppet5-release-$(lsb_release -cs).deb
    apt-get -qq update
    apt-get install -y puppet-agent
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "environments/test/manifests/"
    puppet.manifest_file = "default.pp"
  end

end
